---
image: "buluma/github-action-molecule:4.0.5"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  retry: 1
  parallel:
    matrix:
      - image: "amazonlinux"
        tag: "latest"
      - image: "enterpriselinux"
        tag: "latest"

galaxy:
  script:
    - ansible-galaxy role info ${CI_PROJECT_NAMESPACE}.${CI_PROJECT_NAME}
