---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '9 5 * * *'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: "${{ secrets.SLACK_WEBHOOK_URL }}"
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: "#ansible"
          message: Starting Ansible Epel Molecule Test...
        if: always()
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: buluma/molecule-action@v4.0.6
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "amazonlinux"
            tag: "latest"
          - image: "enterpriselinux"
            tag: "7"
          - image: "enterpriselinux"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
        uses: buluma/molecule-action@v4.0.6
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: "${{ job.status }}"
          steps: "${{ toJson(steps) }}"
          channel: "#ansible"
        if: always()
