---
#
# Ansible managed
#

name: "Test Role"

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/test.yaml'
  schedule:
    - cron: '1 1 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test Role install.
        run: ansible-galaxy install buluma.epel

      - name: Get Role ID.
        run: ansible-galaxy info buluma.epel
