---
#
# Ansible managed
#

name: "Test Role"

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/test.yaml'
  schedule:
    - cron: '51 1,3 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test role install
        run: ansible-galaxy install buluma.epel

      - name: test online role
        run: ansible-galaxy info buluma.ansible_role_prometheus
